flat_full.Rmd:
  path: dev/flat_full.Rmd
  state: active
  R:
  - R/add_favourite.R
  - R/check_api_version.R
  - R/check_extension.R
  - R/check_language.R
  - R/check_status_code.R
  - R/data_serie.R
  - R/delete_favourite.R
  - R/generate_datasets.R
  - R/generate_dimensions.R
  - R/plot_serie.R
  - R/save_output.R
  - R/ya_api_info.R
  - R/ya_get_dataset.R
  - R/ya_get_dataset_item.R
  - R/ya_get_dimension.R
  - R/ya_get_dimension_description.R
  - R/ya_get_dimension_item.R
  - R/ya_get_domain.R
  - R/ya_info_serie.R
  - R/ya_my_favourites.R
  - R/ya_save_dataset.R
  - R/ya_save_dataset_item.R
  - R/ya_save_dimension.R
  - R/ya_save_dimension_description.R
  - R/ya_save_dimension_item.R
  - R/ya_save_domain.R
  - R/ya_search.R
  - R/na.R
  tests:
  - tests/testthat/test-check_language.R
  - tests/testthat/test-check_status_code.R
  - tests/testthat/test-check_api_version.R
  - tests/testthat/test-check_extension.R
  - tests/testthat/test-generate_datasets.R
  - tests/testthat/test-generate_dimensions.R
  - tests/testthat/test-save_output.R
  - tests/testthat/test-plot_serie.R
  - tests/testthat/test-data_serie.R
  - tests/testthat/test-add_favourite.R
  - tests/testthat/test-delete_favourite.R
  - tests/testthat/test-ya_api_info.R
  - tests/testthat/test-ya_get_domain.R
  - tests/testthat/test-ya_save_domain.R
  - tests/testthat/test-ya_get_dataset.R
  - tests/testthat/test-ya_save_dataset.R
  - tests/testthat/test-ya_get_dataset_item.R
  - tests/testthat/test-ya_save_dataset_item.R
  - tests/testthat/test-ya_get_dimension.R
  - tests/testthat/test-ya_save_dimension.R
  - tests/testthat/test-ya_get_dimension_item.R
  - tests/testthat/test-ya_save_dimension_item.R
  - tests/testthat/test-ya_get_dimension_description.R
  - tests/testthat/test-ya_save_dimension_description.R
  - tests/testthat/test-ya_search.R
  - tests/testthat/test-ya_my_favourites.R
  - tests/testthat/test-ya_info_serie.R
  vignettes: vignettes/get-started.Rmd
  inflate:
    pkg: yabpstat
    flat_file: dev/flat_full.Rmd
    vignette_name: Get started
    open_vignette: yes
    check: yes
    document: yes
    overwrite: 'yes'
