# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand


#' Test with your dataset in "datasets/"
#' 
#'\dontrun{
# datafile <- "ya_status_codes.rds"
# 
# if(!file.exists(datafile)){
#   
#   datafile <- file.path("tests", "testthat", datafile)
#   if (!file.exists(datafile)) {stop(datafile, " does not exist.")}
#   
# }
# 
# stat_codes <- readRDS(file = datafile)
# 
# test_that("check_status_code works", {
#   expect_type(check_status_code(200), "list")
#   # expect_error(check_status_code(900), "That status doesn't exists yet.")
# })
# }
