# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand

#' \dontrun{
#' test_that("check_extension works", {
#'   expect_null(check_extension(extension = "rds"))
#'   expect_error(check_extension(extension = "txt")) 
#' })
#' }
