# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand

#' \dontrun{
#' test_that("generate_dimensions works", {
#'   expect_true(inherits(generate_dimensions, "function")) 
#' })
#' }
