# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand


test_that("check_language works", {
  expect_null(check_language(lang = "PT"))
  expect_error(check_language(lang = "FR"))
})

