# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand

#\dontrun{
# test_that("ya_get_domain works", {
#   expect_true(ya_get_domain(lang = "PT")) 
#   expect_error(ya_get_domain(lang = "ES"))
# })
#}
