# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand

#'\dontrun{
#'test_that("ya_get_dimension_item works", {
#'  expect_true(inherits(ya_get_dimension_item, "function")) 
#'})
#'}
