# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand

#'\dontrun{
#' test_that("ya_api_info works", {
#'   expect_message(ya_api_info(lang="PT"))
#'   expect_error(ya_api_info(lang="FR")) 
#' })
#'}
