# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand

#'
#' Title: add_favourite()
#' 
#' Description: This is an helper function that adds series ID from BPstat to users favourites.
#' 
#' @param id A serie ID from the BPstat.
#' @param dataset A dataset corresponding to users favourites
#' 
#' @importFrom httr2 request
#' @importFrom httr2 req_user_agent
#' @importFrom httr2 req_perform
#' @importFrom httr2 resp_status
#' @importFrom dplyr between
#' @importFrom dplyr %>%
#' 
#' @return A success message from a well succeed insertion of a new serie.
#' 
#' @noRd
#' 
add_favourite <- function(id, dataset, lng){
  
  basepath_url <- "https://bpstat.bportugal.pt"
  
  url <- paste0(basepath_url,
           "/api/series/?view_full=true&series_ids=",
           id)

  if (!is.numeric(id)) {
    stop("Wrong data type in \"series_id\" input.")

  }  

  response <- httr2::request(url) %>% 
    httr2::req_user_agent("YABPstat package") %>% 
    httr2::req_perform()

  st_c <- httr2::resp_status(response)
  
  status_description <-
    check_status_code(st_c, lng)
  
  if (dplyr::between(st_c, 300, 550)) {
    stp_msg <- paste0("Estado :",
                      st_c,
                      " - ",
                      status_description,
                      ".")
    
    stop(stp_msg)
  }
  
  dataset[nrow(dataset) + 1,] <- id
  
  dataset <- dataset %>%
    unique()
  
  return(save_output(r_object = dataset,
                    file_directory = "datasets",
                    file_name = "YABPstat_favourites",
                    extension = rds))
  
  message("Record added with success.")
    
}
