# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand

#' Title: check_language()
#' 
#' Description: An helper function that serves as a validation check for user input of the BPstat API supported languages. Currently it uses Portuguese (PT) and English (EN) languages
#' 
#' @param lang A string that represents the languages supported by BPstat API. Currently only uses "PT" or "EN". Defaults to "EN"
#' 
#' @return Returns an error message if user inputs other option than "PT", "pt", "EN" or "en". It doesn't return any message if the task has been successfully accomplished
#' 
#' @noRd
#' 
check_language <- function(lang) {
  if (!(lang %in% c("EN", "en", "PT", "pt"))) {
    err_msg_lang <- paste0(
      "At the moment there is no support for that language.",
      "\n",
      "Please choose between \"PT\" ou \"EN\"."
    )
    stop(err_msg_lang)
  }
  
}

