# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand

#' Title: check_status_code()
#' 
#' Description: An helper function that checks the response call to BPstat API, used in many different functions in the YABPstat package.
#' 
#' @param st_code Status code returned by a call to BPstat API
#' @param lang A string that represents the languages supported by BPstat API. Currently only uses "PT" or "EN". Defaults to "EN"
#' 
#' @importFrom dplyr filter
#' @importFrom dplyr select
#' @importFrom dplyr %>%
#' 
#' @return Returns a string with the description in Portuguese or English languages, of the status code returned from BPstat API call.
#' 
#' @noRd
#' 
#' @examples
#' \dontrun{
#' #'check_status_code(200)
#' }
check_status_code <- function(st_code, lang = "EN") {

  check_language(lang)
  
  stat_codes <- readRDS("data/ya_status_codes.rds")
  
  stat_codes <- stat_codes %>%
      dplyr::filter(status_code == st_code)
  
  if (length(stat_codes) == 0){
    
    stop("That status doesn't exists yet.")
    
  } else if (lang == "EN" | lang == "en") {
    
    stat_codes <- stat_codes %>%
      dplyr::select(description_en)
    
    return(stat_codes)
    
  } else if (lang == "PT" | lang == "pt") {
    
    stat_codes <- stat_codes %>%
      dplyr::select(description_pt)
    
    return(stat_codes)
    
  }
}

