# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand

#' Title: check_extension
#' 
#' Description: This is an helper function that checks if the save output function complies with the requirements of saving files with rds or csv extensions
#' 
#' @param extension A string that represents an extension to save information in BPstat to an external file. At the moment there is support only to rds and csv extensions.
#' 
#' @return An error message if it is any other format besides rds or csv. Nothing if it all goes well.
#' 
#' @noRd
#' 
#' @examples
#' \dontrun{
#' check_extension()
#' }
check_extension <- function(extension) {
  if (!(extension %in% c("RDS", "rds", "csv", "CSV"))) {
    err_msg_extension <- paste0(
      "The extension is not supported, yet.",
      "\n",
      "Please choose between \"rds\" or \"csv\"."
    )
    stop(err_msg_extension)
  }
  
}

