# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand


#' Title: check_api_version()
#' 
#' Description: An helper function that checks for the BPstat Data API version present in "https://bpstat.bportugal.pt/data/docs?format=openapi"
#' 
#' @param bpstat_api_version A string that represents version of current BPStat API
#' 
#' @return Returns an message with the current API version
#' 
#' @noRd
#' 
#' @examples
#' \dontrun{
#' #'check_api_version()
#' }
check_api_version <- function(bpstat_api_version) {
  if (bpstat_api_version[[2]][[3]] == "v1") {
    return("v1")
    
  } else {
    return(bpstat_api_version[[2]][[3]])
  }
}
