# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand

#'
#' Title: delete_favourite
#' 
#' Description: This is an helper function that delete BPstat series ID from users favourites.
#' 
#' @param id A serie ID from the BPstat.
#' @param dataset A dataset corresponding to users favourites
#' 
#' @importFrom httr2 request
#' @importFrom httr2 req_user_agent
#' @importFrom httr2 req_perform
#' @importFrom httr2 resp_status
#' @importFrom dplyr between
#' @importFrom dplyr %>%
#' 
#' @return A success message from a well succeed deletion of a serie.
#' 
#' @noRd
#' 
delete_favourite <- function(id, dataset){
  
  basepath_url <- "https://bpstat.bportugal.pt"
  
  url <- paste0(basepath_url,
           "/api/series/?view_full=true&series_ids=",
           id)

  #check if series_id is numeric
  if (!is.numeric(id)) {
    stop("Wrong data type in \"series_id\" input.")
    
  }
  
  response <- httr2::request(url) %>% 
    httr2::req_user_agent("YABPstat package") %>% 
    httr2::req_perform()
  
  st_c <- httr2::resp_status(response)
  
  status_description <-
    check_status_code(st_c, lang)
  
  if (dplyr::between(st_c, 300, 550)) {
    stp_msg <- paste0("Estado :",
                      st_c,
                      " - ",
                      status_description,
                      ".")
    
    stop(stp_msg)
  }
  
  if (nrow(dataset) == 0) {
    stop("Attention: there is no record to delete.")
  }
  
  dataset <- subset(dataset, dataset$series_id == id)
  
  return(
    saveRDS(object = dataset,
            file = "ya_favourites.rds")
  )
  
  message("Record deleted with success.")
    
}
