# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand


#' Title: generate_dimensions()
#' 
#' Description: This is an helper function that given an href from a BPstat dimension, it returns a dataframe with the follow information: version, href, class, source, item label, item class, item href 
#' 
#' @param dimensions_href An href that represents the path to a dimension in BPstat
#' 
#' @importFrom httr2 request
#' @importFrom httr2 req_user_agent
#' @importFrom httr2 req_perform
#' @importFrom jsonlite fromJSON
#' @importFrom jsonlite flatten
#' @importFrom dplyr mutate
#' @importFrom dplyr %>%
#' 
#' @return A dataframe with information about dimensions, namely: version, href, class, source, item label, item class and item href
#' 
#' @noRd
#' 
generate_dimensions <- function(dimensions_href){
  
  max_datasets <- 100
  
  url <- paste0(dimensions_href, "&page_size=", max_datasets)
  
  response <- httr2::request(url) %>% 
    httr2::req_user_agent("YABPstat package") %>% 
    httr2::req_perform()

  bpstat_dimensions <- jsonlite::fromJSON(rawToChar(response$body))
  
  bpstat_dimensions_item <-
    jsonlite::flatten(bpstat_dimensions$link$item$extension)
  
  bpstat_dimensions_item <- bpstat_dimensions_item %>%
    dplyr::mutate(version = bpstat_dimensions$version,
                  dimensions_href = bpstat_dimensions$href,
                  class = bpstat_dimensions$class,
                  source = bpstat_dimensions$source,
                  item_label = bpstat_dimensions$link$item$label,
                  item_class = bpstat_dimensions$link$item$class,
                  item_href = bpstat_dimensions$link$item$href)
  
  return(bpstat_dimensions_item)
    
}

