# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand

#' status codes
#'
#' data in 'datasets'.
#'
#' @format A data frame with 63 rows and 3 variables representing the avaliable status codes in Portuguese and English languages:
#' \describe{
#'   \item{ status_code }{  character }
#'   \item{ description_en }{  character }
#'   \item{ description_pt }{  character }
#' }
#' @source https://developer.mozilla.org/en-US/docs/Web/HTTP/Status & https://developer.mozilla.org/pt-BR/docs/Web/HTTP/Status.
#' 
