# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand

#' ya_status_codes
#'
#' data in top_level.
#'
#' @format A data frame with 63 rows and 3 variables representing the available status codes in Portuguese and English languages:
#' \describe{
#'   \item{ status_code }{  character }
#'   \item{ description_en }{  character }
#'   \item{ description_pt }{  character }
#' }
#' @source https://developer.mozilla.org/en-US/docs/Web/HTTP/Status & https://developer.mozilla.org/pt-BR/docs/Web/HTTP/Status.
#' 
#' "ya_status_codes"


#' ya_favourites
#'
#' data in top_level.
#'
#' @format A data frame with 15 rows and 1 variable, choosen from BPstat observations carousel, representing the user's favourite series ID from BPstat:
#' \describe{
#'   \item{ series_id }{  numeric }
#' }
#' @source YABPstat
#' 
#'"ya_favourites" 

