# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand

#'
#' Title: plot_serie()
#' 
#' Description: This is an helper function to plot series from the main function ya_info_serie()
#' 
#' @param id A serie ID from the BPstat.
#' @param lng A string that represents the languages supported by BPstat API. Currently only uses "PT" or "EN". Defaults to "EN"
#' 
#' @importFrom httr2 request
#' @importFrom httr2 req_user_agent
#' @importFrom httr2 req_perform
#' @importFrom httr2 resp_status
#' @importFrom dplyr between
#' @importFrom dplyr %>%
#' @importFrom dplyr tibble
#' @importFrom tidyr unnest_longer
#' @importFrom tidyr unnest_wider
#' @importFrom dplyr mutate
#' @importFrom dplyr across
#' @importFrom dplyr select
#' @importFrom dplyr rename
#' @importFrom jsonlite fromJSON
#' @importFrom jsonlite read_json
#' @importFrom xts xts
#' @importFrom dygraphs dygraph
#' 
#' @return A plot with the data gather from BPstat from the designated serie, chosen by the user
#' 
#' @noRd
#' 
#' @examples
#' 
#' #'\dontrun{
#' plot_serie()
#' }
plot_serie <- function(id, lng){
  
  basepath <- "https://bpstat.bportugal.pt"
  
  # todos os valores da s\u00e9rie selecionada
  url_sv <- paste0(basepath,
                   "/api/observations/?series_ids=",
                   id)
  
  # titulos e etiquetas das s\u00e9ries
  url_sfv <- paste0(basepath,
                    "/api/series/?view_full=true&page_size=1&series_ids=",
                    id)

  response <- httr2::request(url_sfv) %>%
    httr2::req_user_agent("YABPstat package") %>%
    httr2::req_perform()

  st_c <- httr2::resp_status(response)
  
  status_description <-
    check_status_code(st_c, lang)
  
  if (dplyr::between(st_c, 300, 550)) {
    stp_msg <- paste0("Estado :",
                      st_c,
                      " - ",
                      status_description,
                      ".")
    
    stop(stp_msg)
  }

  url_sv_json <- jsonlite::read_json(url_sv)
  
  df_plot <- url_sv_json %>%
    dplyr::tibble() %>%
    tidyr::unnest_longer(1) %>%
    tidyr::unnest_wider(1) %>%
    dplyr::mutate(dplyr::across(reference_date, as.Date)) %>%
    dplyr::select(reference_date, value) %>%
    dplyr::rename(ds = reference_date, y = value)
  
  url_sfv_json <- jsonlite::fromJSON(url_sfv)
  
  if (lang == "EN" || lang == "en") {
    titulo <- url_sfv_json[["data"]][["title"]][["EN"]]
    
    
  } else {
    titulo <- url_sfv_json[["data"]][["title"]][["PT"]]
    
  }

  dados <- xts::xts(x = df_plot$y, order.by = df_plot$ds)
  
  
  dygraphs::dygraph(dados, main = titulo) %>%
    dyOptions(
      labelsUTC = TRUE,
      drawGrid = TRUE,
      colors = "#8F733C",
      drawPoints = TRUE,
      pointSize = 2
    ) %>%
    dyRangeSelector(height = 40) %>%
    dyCrosshair(direction = "vertical") %>%
    dyAxis("x",
           drawGrid = FALSE,
           gridLineColor = "#808080") %>%
    dyAxis("y", valueRange = c(min(as.numeric(df_plot$y)), max(as.numeric(df_plot$y))))
  
}
