# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand

#'
#' Title: save_output
#' 
#' Description: An helper function that allows easyly saving data from YABPstat functions to user's local folder for further use. By default it creates a "data/raw/" folder. 
#' 
#' @param r_object The name of the R object to save
#' @param file_directory The default folder name where the file is saved. Defaults to: "data/raw/"
#' @param file_name The name of the file to be saved
#' @param extension The extension name which the file is saved. It only supports "rds" and "csv" for the moment. Defaults to "rds".
#' 
#' @return A file with extension "rds" or "csv"
#' 
#' @noRd
#' @examples
#' #'\dontrun{
#' save_output()
#' #'
#' #'}

save_output <- function(r_object, file_directory = "raw", file_name, extension = "rds"){
  
  check_extension(extension)
  
  if (!dir.exists(paste0(getwd(),
                         "/data/",
                         file_directory))) {
    dir.create(file.path("data", file_directory), recursive = TRUE)
  }
  
  if (extension == "rds" || extension == "RDS") {
    saveRDS(
      object = r_object,
      file = paste0(getwd(),
                    "/data/",
                    file_directory,
                    "/",
                    file_name,
                    ".rds")
    )
  } else if (extension == "csv" || extension == "CSV") {
    write.csv(
      r_object,
      file = paste0(getwd(),
                    "/data/",
                    file_directory,
                    "/",
                    file_name,
                    ".csv"),
      row.names = TRUE
    )
    
  }
  
}
