# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand


#' Title: ya_api_info()
#' 
#' Description: Shows useful informations such as type, status code and description, and version of current BPstat Data API.
#' 
#' @param lang  A string that represents the languages supported by BPstat API. Currently only uses "PT" or "EN". Defaults to "EN"
#' 
#' @importFrom httr2 request
#' @importFrom httr2 req_user_agent
#' @importFrom httr2 req_perform
#' @importFrom httr2 resp_status
#' @importFrom jsonlite fromJSON
#' @importFrom dplyr %>%
#' 
#' @return  A string with type, status code and description, and api version in Portuguese an English languages, and a generalized error message to check internet connection.
#' 
#' @export
#' 
#' @examples
#' ya_api_info()
ya_api_info <- function(lang = "EN") {
  
  lang <- "PT"
  
  check_language(lang)
  
  basepath_url <- "https://bpstat.bportugal.pt"
  
  url <- paste(basepath_url,
                      "/data/docs/?format=openapi",
                      sep = "")
  
  tryCatch({
    
    response <- httr2::request(url) %>% 
      httr2::req_user_agent("YABPstat package") %>% 
      httr2::req_perform()
    
    type <- response %>% 
      httr2::resp_content_type()    

    api_version <-
      check_api_version(jsonlite::fromJSON(url))

    st_c <- httr2::resp_status(response)

    status_description <-
      check_status_code(st_c, lang)
    
    if (lang == "EN" || lang == "en") {
      if (api_version == "v1") {
        msg_api <- paste0(
          "API type: ",
          type,
          ".\n",
          "Status: ",
          st_c,
          " - ",
          status_description,
          "\n",
          "API version: ",
          api_version,
          "."
        )
        
        message(msg_api)
        
      } else {
        msg_api <- paste0(
          "API type: ",
          type,
          ".\n",
          "Status: ",
          st_c,
          " - ",
          status_description,
          "\n",
          "API version not supported: ",
          api_version,
          "."
        ) 
        warning(msg_api)
        
      }
      
    } else if (lang == "PT" || lang == "pt") {
      if (api_version == "v1") {
        msg_api <- paste0(
          "Tipo da API: ",
          type,
          ".\n",
          "Estado: ",
          st_c,
          " - ",
          status_description,
          "\n",
          "\u0056\u0065\u0072\u0073\u00e3\u006f da API: ",
          api_version,
          "."
        )
        
        message(msg_api)
        
      } else {
        msg_api <- paste0(
          "Tipo da API: ",
          type,
          ".\n",
          "Estado: ",
          st_c,
          " - ",
          status_description,
          "\n",
          "\u0056\u0065\u0072\u0073\u00e3\u006f da API \u006e\u00e3\u006f suportada: ",
          api_version,
          "."
        )
        
        warning(msg_api)
        
      }
      
    }
    
  }, error = function(e) {
    if (lang == "EN" || lang == "en") {
      err_msg <- paste0("Error: ",
                        "\n",
                        "Something went wrong. Please contact the maintainer.")
      
    } else {
      err_msg <- paste0("Erro: ",
                        "\n",
                        "Aconteceu um erro inesperado. Por favor entre em contacto com a equipa de desenvolvimento.")
      
    }
    stop(err_msg)
    
  })
  
}

