# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand


#' Title: ya_get_domain()
#' 
#' Description: This function gathers information about BPstat domains and makes visible to the user in a table format for better visualization and comprehension. The returned fields are: 
#' ID - The unique ID of the domain in the BPstat structure and identification.
#' Parent ID - The ID of the parent section (none if it is a top level domain)
#' Order - The order where it is displayed in the BPstat theme organization
#' Label - The label of the domain
#' Short label - Short label of the domain 
#' Description - The domain description
#' Has series - If the domain has series (True if it has, False if it has not)
#' Last update - Last date when the domain has been updated
#' Number of series - Number of series that the domain has
#' Number of datasets - Number of datasets that the domain has
#' Domain URL - The Uniform Resource Location of the domain in BPstat
#' Dataset URL - The Uniform Resource Location of the dataset in BPstat
#' Dimension URL - The Uniform Resource Location of the dimension in BPstat
#' 
#' @param lang A string that represents the languages supported by BPstat API. Currently only uses "PT" or "EN". Defaults to "EN"
#' 
#' @importFrom httr2 request
#' @importFrom httr2 req_user_agent
#' @importFrom httr2 req_perform
#' @importFrom httr2 resp_status
#' @importFrom httr2 resp_body_raw
#' @importFrom jsonlite fromJSON
#' @importFrom dplyr between
#' @importFrom dplyr %>%
#' @importFrom dplyr tibble
#' @importFrom DT datatable
#' @importFrom htmltools tag
#' 
#' @return A DT table in the RStudio viewer
#' 
#' @export
#' 
#' @examples
#' ya_get_domain()
ya_get_domain <- function(lang = "EN"){
  
  check_language(lang)
  
  temp_df <- dplyr::tibble()
  
  basepath_url <- "https://bpstat.bportugal.pt"
  
  url <- paste0(basepath_url,
              "/data/v1/domains/?lang=",
              toupper(lang))
  
  tryCatch({
    
    response <- httr2::request(url) %>% 
      httr2::req_user_agent("YABPstat package") %>% 
      httr2::req_perform()
    
    st_c <- httr2::resp_status(response)

    status_description <-
      check_status_code(st_c, lang)
    
    if (dplyr::between(st_c, 400, 550)) {
      stp_msg <- paste0("Estado :",
                        st_c,
                        " - ",
                        status_description,
                        ".")
      
      stop(stp_msg)
      
    } else {
      raw_response <- httr2::resp_body_raw(response)
    
      temp_df <- jsonlite::fromJSON(rawToChar(raw_response))
      
      if (lang == "EN" || lang == "en") {
        column_names <- c(
          "ID",
          'Parent ID',
          'Order',
          'Label',
          'Short label',
          'Description',
          'Has series',
          'Last update',
          'Number of series',
          'Number of datasets',
          'Domain URL',
          'Dataset URL',
          'Dimension URL'
        )
        
        capt <- "YABPstat: List of domains"
        
        translate_to <-
          '//cdn.datatables.net/plug-ins/1.10.11/i18n/English.json'
        
      } else if (lang == "PT" || lang == "pt") {
        column_names <- c(
          "ID",
          'N\u00f3 pai',
          'Ordem',
          'Etiqueta',
          'Abreviatura',
          'Descri\u00e7\u00e3o',
          'Tem s\u00e9ries',
          'Ultima atualiza\u00e7\u00e3o',
          'N\u00famero de s\u00e9ries',
          'N\u00famero de datasets',
          'URL do dom\u00ednio',
          'URL do dataset',
          'URL da dimens\u00e3o'
        )
        
        capt <- "YABPstat: Lista de dominios"
        
        translate_to <-
          '//cdn.datatables.net/plug-ins/1.10.11/i18n/Portuguese-Brasil.json'
        
      } else {
        err_msg <- paste0("O idioma ainda n\u00e3o \u00e9 suportado.",
                          "\n",
                          "Por favor escolha entre \"EN\" ou \"PT\".")
        stop(err_msg)
        
      }
      
      DT::datatable(
        data = temp_df,
        style = "auto",
        class = "cell-border stripe",
        caption = htmltools::tags$caption(
          style = "caption-side: top;
                  text-align: center;
                  color:black;  font-size:200% ;
                  padding-top: 20px;
                  padding-bottom: 15px;",
          capt
        ),
        rownames = FALSE,
        colnames = column_names,
        options = list(
          columnDefs = list(list(
            className = 'dt-center', targets = c(0:12)
          )),
          searchHighlight = TRUE,
          search = list(regex = TRUE),
          language = list(url = translate_to)
        )
      )
    }
    
    
  }, error = function(e) {
    if (lang == "EN" || lang == "en") {
      err_msg <- paste0("Error: ",
                        "\n",
                        "Something went wrong. Please contact the maintainer.")
      
    } else {
      err_msg <- paste0("Erro: ",
                        "\n",
                        "Aconteceu um erro inesperado. Por favor entre em contacto com a equipa de desenvolvimento.")
      
    }
    stop(err_msg)
    
  })
  
    
}

