# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand


#' Title: ya_get_dimension_item()
#' 
#' Description: A function that gathers information available in BPstat about the dataset items.
#' 
#' @param lang  A string that represents the languages supported by BPstat API. Currently only uses "PT" or "EN". Defaults to "EN"
#' 
#' @importFrom httr2 request
#' @importFrom httr2 req_user_agent
#' @importFrom httr2 req_perform
#' @importFrom httr2 resp_status
#' @importFrom httr2 resp_body_raw
#' @importFrom dplyr between
#' @importFrom dplyr select
#' @importFrom dplyr tibble
#' @importFrom dplyr %>%
#' @importFrom tidyr drop_na
#' @importFrom jsonlite fromJSON
#' @importFrom htmltools tags
#' @importFrom DT datatable
#' @importFrom knitr kable
#' 
#' @return A data table with the information in a more human readable form with a search option using regex.
#' 
#' @export
#' 
#' @examples
#' #'ya_get_dimension_item()
ya_get_dimension_item <- function(lang = "EN"){
  
  check_language(lang)
  
  df_data <- dplyr::tibble()
  
  temp_df <- dplyr::tibble()
  
  basepath_url <- "https://bpstat.bportugal.pt"
  
  url <- paste0(basepath_url,
                "/data/v1/domains/?lang=",
                toupper(lang))
  
  tryCatch({
    response <- httr2::request(url) %>%
      httr2::req_user_agent("YABPstat package") %>%
      httr2::req_perform()
    
    st_c <- httr2::resp_status(response)
    
    status_description <-
      check_status_code(st_c, lang)
    
    if (dplyr::between(st_c, 300, 550)) {
      stp_msg <- paste0("Estado :",
                        st_c,
                        " - ",
                        status_description,
                        ".")
      
      stop(stp_msg)
      
      
    } else {
      raw_response <- httr2::resp_body_raw(response)
      
      temp_df <- jsonlite::fromJSON(rawToChar(raw_response))
      
      temp_df <- temp_df %>%
        dplyr::select(dimensions_href, num_series) %>%
        tidyr::drop_na()
      
      if (lang == "EN" || lang == "en") {
        column_names <- c('Description', "Item label", "Item URL")
        
        capt <-
          "YABPstat: Information about dimensions"
        
        translate_to <-
          '//cdn.datatables.net/plug-ins/1.10.11/i18n/English.json'
        
      } else {
        column_names <- c("Descri\u00e7\u00e3o", "Item", "URL do item")
        
        capt <-
          "YABPstat: Informa\u00e7\u00e3o acerca das dimens\u00f5es"
        
        translate_to <-
          '//cdn.datatables.net/plug-ins/1.10.11/i18n/Portuguese-Brasil.json'
        
      }
      
      for (row in 1:nrow(temp_df)) {
        df_data <- rbind(df_data,
                         generate_dimensions(temp_df$dimensions_href[[row]]))
      }
      
      
      df_data <-
        df_data %>% dplyr::select(description,
                                  item_label,
                                  item_href)
      if (commandArgs()[1] == "RStudio") {
        DT::datatable(
          data = df_data,
          style = "auto",
          class = "cell-border stripe",
          caption = htmltools::tags$caption(
            style = "caption-side: top;
                  text-align: center;
                  color:black;  font-size:200% ;
                  padding-top: 20px;
                  padding-bottom: 15px;",
            capt
          ),
          rownames = FALSE,
          colnames = column_names,
          options = list(
            columnDefs = list(list(
              className = 'dt-center', targets = c()
            )),
            searchHighlight = TRUE,
            search = list(regex = TRUE),
            language = list(url = translate_to)
          )
        )
      } else {
        knitr::kable(x = df_data,
                     caption = capt,
                     col.names = column_names, 
                     align = "lll", 
                     format = "pipe")
        
      }
    }
  }, error = function(e) {
    if (lang == "EN" || lang == "en") {
      err_msg <- paste0("Error: ",
                        "\n",
                        "Something went wrong. Please contact the maintainer.")
      
    } else {
      err_msg <- paste0(
        "Erro: ",
        "\n",
        "Aconteceu um erro inesperado. Por favor entre em contacto com a equipa de desenvolvimento."
      )
      
    }
    stop(err_msg)
    
  })
  
}

