# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand

#'
#' Title: ya_info_serie()
#' 
#' Description: A function allows to user to plot, see in a table or reuse in other context, data from a determined BPstat serie ID.
#' 
#' @param series_id A serie ID from BPstat. Defaults to 0 (zero)
#' @param operation A string with the length of 1 (one), representing the following operations:
#'                      P - plot
#'                      T - table
#'                      Df - dataframe
#' @param lang  A string that represents the languages supported by BPstat API. Currently only uses "PT" or "EN". Defaults to "EN"
#' 
#' @importFrom httr2 request
#' @importFrom httr2 req_user_agent
#' @importFrom httr2 req_perform
#' @importFrom httr2 resp_status
#' @importFrom dplyr between
#' @importFrom dplyr %>%
#' @importFrom dplyr tibble
#' @importFrom dplyr mutate
#' @importFrom dplyr across
#' @importFrom dplyr select
#' @importFrom tidyr unnest_longer
#' @importFrom tidyr unnest_wider
#' @importFrom jsonlite read_json
#' 
#' @return From the user choice can be a plot, a table or a tibble for further analysis
#' 
#' @export
#' 
#' @examples
#' #'\dontrun{
#' #'ya_info_serie(series_id = 12528985)
#' #'}
ya_info_serie <- function(series_id = 0, operation = "P", lang = "EN"){
  
  check_language(lang)
  
  if (!(operation %in% c("P", "p", "T", "t", "Df", "df"))) {
    stop(
      "Wrong type of operation. \nPlease choose between \"P\" - plot, \"T\" - table and \"Df\" - dataframe."
    )
  }
  
  if ((operation == "P" |
       operation == "p") & !(series_id == 0)) {
    plot_serie(id = series_id, lng = lang)
    
  } else if (operation == "T" |
             operation == "t" & !(series_id == 0)) {
    data_serie(id = series_id, lng = lang)
    
  } else if (operation == "Df" |
             operation == "df" & !(series_id == 0)) {
    df_data <- dplyr::tibble()
    
    basepath <- "https://bpstat.bportugal.pt"
    
    url_sv <- paste0(basepath,
                     "/api/observations/?series_ids=",
                     series_id)
    
    response <- httr2::request(url_sv) %>% 
      httr2::req_user_agent("YABPstat package") %>% 
      httr2::req_perform()
    
    st_c <- httr2::resp_status(response)
    
    status_description <-
      check_status_code(st_c, lang)
    
    if (dplyr::between(st_c, 300, 550)) {
      stp_msg <- paste0("Estado :",
                        st_c,
                        " - ",
                        status_description,
                        ".")
      
      stop(stp_msg)
    }
    
    url_sv_json <- jsonlite::read_json(url_sv)
    
    df_data <- url_sv_json %>%
      dplyr::tibble() %>%
      tidyr::unnest_longer(1) %>%
      tidyr::unnest_wider(1) %>%
      dplyr::mutate(dplyr::across(reference_date, as.Date),
                    dplyr::across(pub_date, as.Date)) %>%
      dplyr::select(-c(series_id, privacy_code, is_highlighted, description))
    
    return(df_data)
    
    message(
      "The dataframe contains the following variables:\n
                id,\n
                version_id,\n
                value,\n
                reference_date,\n
                pub_date."
    )
    
  } else {
    stop("Please check your arguments. There's something wrong.")
  }
 
}
