# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand


#' Title: ya_save_domain()
#' 
#' Description: A function that saves de information avaliable about the BPstat domains
#' 
#' @param lang  A string that represents the languages supported by BPstat API. Currently only uses "PT" or "EN". Defaults to "EN"
#' @param extension A string that represents the avaliable extensions to save files. Currently only uses "rds" or "csv". Defaults to "rds"
#' 
#' @importFrom httr2 request
#' @importFrom httr2 req_user_agent
#' @importFrom httr2 req_perform
#' @importFrom httr2 resp_status
#' @importFrom httr2 resp_body_raw
#' @importFrom dplyr between
#' @importFrom dplyr %>%
#' @importFrom jsonlite fromJSON
#' 
#' @return A file with the available data from the domains in the rds or csv format.
#' 
#' @export
#' 
#' @examples
#' #'\dontrun{
#' #'ya_save_domain()
#' #'}
ya_save_domain <- function(lang = "EN", extension = "rds"){
  
  check_language(lang)
  
  check_extension(extension)

  basepath_url <- "https://bpstat.bportugal.pt"
  
  url <- paste0(basepath_url,
                "/data/v1/domains/?lang=",
                toupper(lang))
  
  response <- httr2::request(url) %>% 
    httr2::req_user_agent("YABPstat package") %>% 
    httr2::req_perform()
  
  st_c <- httr2::resp_status(response)
  
  status_description <-
    check_status_code(st_c, lang)
  
  if (dplyr::between(st_c, 400, 550)) {
    stp_msg <- paste0("Estado :",
                      st_c,
                      " - ",
                      status_description,
                      ".")
    
    stop(stp_msg)
    
  } else {
    
    raw_response <- httr2::resp_body_raw(response)
    
    temp_df <- jsonlite::fromJSON(rawToChar(raw_response))
    
    return(
      save_output(
        r_object = temp_df,
        file_directory = "raw",
        file_name = "bpstat_domains",
        extension = extension
      )
    )
  }
    
}

