# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand


#' Title: ya_search()
#' 
#' Description: This is a function that allows to the user search directly de BPstat data through the API.

#' @param query A string that represents a query to be executed in BPstat
#' @param lang A string that represents the languages supported by BPstat API. Currently only uses "PT" or "EN". Defaults to "EN"
#' 
#' @importFrom utils URLencode
#' @importFrom httr2 request
#' @importFrom httr2 req_user_agent
#' @importFrom httr2 req_perform
#' @importFrom httr2 resp_status
#' @importFrom httr2 resp_body_json
#' @importFrom dplyr between
#' @importFrom dplyr tibble
#' @importFrom dplyr %>%
#' @importFrom dplyr select
#' @importFrom dplyr mutate
#' @importFrom dplyr relocate
#' @importFrom DT datatable
#' @importFrom htmltools tags
#' @importFrom knitr kable
#' 
#' @return A data table with the query results from BPstat.
#' 
#' @export
#' 
#' @examples
#' #'ya_search(query="ihpc")
ya_search <- function(query, lang = "EN"){
  
  check_language(lang)
  
  page_size <- 50
  
  basepath <-
    "https://bpstat.bportugal.pt/api/search/?search="
  
  q <- paste0(
    basepath,
    utils::URLencode(query),
    "&code=VET&language=",
    toupper(lang),
    "&page=1&page_size=",
    page_size
  )
  
  
  if (nchar(query) < 3) {
    if (lang == "EN" || lang == "en") {
      err_msg <- paste0(
        "Not enough letters to make a query.",
        "\n",
        "To obtain any results, please use more than 3 characters in the query."
      )
      
    } else {
      err_msg <-
        paste0(
          "N\u00famero de caracteres insuficiente para realizar a pesquisa.",
          "\n",
          "Para obten\u00e7\u00e3o de resultados, por favor utilize termos de pesquisa com, pelo menos, 3 caracteres."
        )
      
    }
    stop(err_msg)
    
  } else if (nchar(query) > 200) {
    stop("The query is limited to 200 characters. Please choose the words wisely.")
    
  }
  
  response <- httr2::request(q) %>%
    httr2::req_user_agent("YABPstat package") %>%
    httr2::req_perform()
  
  st_c <- httr2::resp_status(response)
  
  status_description <-
    check_status_code(st_c, lang)
  
  if (dplyr::between(st_c, 300, 550)) {
    stp_msg <- paste0("Estado :",
                      st_c,
                      " - ",
                      status_description,
                      ".")
    
    stop(stp_msg)
    
  }
  
  raw_response <-  response %>%
    httr2::resp_body_json()
  
  if (raw_response$count == 0) {
    message("There's no results to show.")
    
  } else {
    if ((raw_response$count - 1) < page_size) {
      num_pages <- 1
      
    } else if ((raw_response$count - 1) > page_size) {
      if (((raw_response$count - 1) %% page_size) == 0) {
        num_pages <- as.integer((raw_response$count - 1) / page_size)
        
      } else {
        num_pages <- as.integer(((raw_response$count - 1) / page_size) + 1)
        
      }
      
    }
    
    tryCatch({
      df_data <- dplyr::tibble()
      
      for (pag in 1:num_pages) {
        results <- NULL
        
        q <- paste0(
          basepath,
          utils::URLencode(query),
          "&code=VET&language=",
          toupper(lang),
          "&page=",
          pag,
          "&page_size=",
          page_size
        )
        
        results <- httr2::request(q) %>%
          httr2::req_user_agent("YABPstat package") %>%
          httr2::req_perform() %>%
          httr2::resp_body_json()
        
        df_data <-
          rbind(df_data, as.data.frame(do.call(rbind, results$data)))
        
      }
      
      if (lang == "EN" || lang == "en") {
        column_names <- c("Link", "Title", "Description", "Publication")
        
        capt <- "YABPstat: Search results"
        
        translate_to <-
          '//cdn.datatables.net/plug-ins/1.10.11/i18n/English.json'
        
      } else {
        column_names <-
          c(
            "Liga\u00e7\u00e3o",
            "T\u00edtulo",
            "Descri\u00e7\u00e3o",
            "Publica\u00e7\u00e3o"
          )
        
        capt <- "YABPstat: Resultados da pesquisa"
        
        translate_to <-
          '//cdn.datatables.net/plug-ins/1.10.11/i18n/Portuguese-Brasil.json'
        
      }
      
      df_data <- df_data %>%
        dplyr::select(id, title, description, pub_date) %>%
        dplyr::mutate(
          link = paste0(
            "<a href=https://bpstat.bportugal.pt/serie/",
            id,
            " target=\"_blank\">",
            id,
            "</a>"
          )
        ) %>%
        dplyr::relocate(link, .before = title) %>%
        dplyr::select(-c(id))
      
      if (commandArgs()[1] == "RStudio") {
        DT::datatable(
          data = df_data,
          style = 'auto',
          class = 'cell-border stripe',
          caption = htmltools::tags$caption(
            style = 'caption-side: top;
                        text-align: center;
                        color:black;  font-size:200% ;
                        padding-top: 20px;
                        padding-bottom: 15px;',
            capt
          ),
          rownames = FALSE,
          escape = FALSE,
          colnames = column_names,
          options = list(
            columnDefs = list(list(
              className = 'dt-center', targets = c(0)
            )),
            searchHighlight = TRUE,
            search = list(regex = TRUE),
            language = list(url = translate_to)
          )
        )
      } else {
        knitr::kable(x = df_data,
                     caption = capt,
                     col.names = column_names, 
                     align = "lllc", 
                     format = "pipe")
        
      }
      
    }, error = function(e) {
      if (lang == "EN" || lang == "en") {
        err_msg <- paste0("Error: ",
                          "\n",
                          "Something went wrong. Please contact the maintainer.")
        
      } else {
        err_msg <- paste0(
          "Erro: ",
          "\n",
          "Aconteceu um erro inesperado. Por favor entre em contacto com a equipa de desenvolvimento."
        )
        
      }
      stop(err_msg)
      
    })
  }
}

