# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand


#' Title ya_save_dimension_description()
#' 
#' Description: A function that saves de information available about the BPstat description of dimensions.
#' 
#' @param lang  A string that represents the languages supported by BPstat API. Currently only uses "PT" or "EN". Defaults to "EN"
#' @param extension A string that represents the available extensions to save files. Currently only uses "rds" or "csv". Defaults to "rds"
#'
#' @importFrom httr2 request
#' @importFrom httr2 req_user_agent
#' @importFrom httr2 req_perform
#' @importFrom httr2 resp_status
#' @importFrom httr2 resp_body_raw
#' @importFrom dplyr between
#' @importFrom dplyr tibble
#' @importFrom dplyr %>%
#' @importFrom jsonlite fromJSON
#' @importFrom tidyr drop_na
#' 
#' @return A file with the information about BPstat description of dimensions with the rds or csv extension.
#' 
#' @export
#' 
#' @examples
#' #'ya_save_dimension_description()
ya_save_dimension_description <- function(lang = "EN", extension = "rds"){
  
  check_language(lang)
  
  check_extension(extension)
  
  tmp_dset_df <- data.frame()
  
  temp_df <- data.frame()
  
  basepath_url <- "https://bpstat.bportugal.pt"
  
  url <- paste0(basepath_url,
                "/data/v1/domains/?lang=",
                toupper(lang))
  
  response <- httr2::request(url) %>% 
    httr2::req_user_agent("YABPstat package") %>% 
    httr2::req_perform()
  
  st_c <- httr2::resp_status(response)
  
  status_description <-
    check_status_code(st_c, lang)
  
  if (dplyr::between(st_c, 300, 550)) {
    stp_msg <- paste0("Estado :",
                      st_c,
                      " - ",
                      status_description,
                      ".")
    
    stop(stp_msg)
    
  } else {
    raw_response <- response %>% 
      httr2::resp_body_raw()
    
    temp_df <- jsonlite::fromJSON(rawToChar(raw_response))
    
    temp_df <- temp_df %>%
      dplyr::select(dimensions_href, num_series) %>%
      tidyr::drop_na()
    
    for (row in 1:nrow(temp_df)) {
      tmp_dset_df <- rbind(tmp_dset_df,
                           generate_dimensions(temp_df$dimensions_href[[row]]))
    }
    
    tmp_dset_df <- tmp_dset_df %>% dplyr::select(item_href)
    
    full_df <- dplyr::tibble()
    
    for (row in 1:nrow(tmp_dset_df)) {
      tryCatch({
        tmp_df <- NULL
        
        get_description <- httr2::request(tmp_dset_df[row, ]) %>% 
          httr2::req_user_agent("YABPstat package") %>% 
          httr2::req_perform()
        
        raw_get_description <- httr2::resp_body_raw(get_description)
        
        contents <-
          jsonlite::fromJSON(rawToChar(raw_get_description))
        
        tmp_lst <-
          do.call(rbind, contents$category$label)
        
        tmp_df <- as.data.frame(tmp_lst) %>%
          dplyr::rename(value = V1)
        
        tmp_df <-
          cbind(label = rownames(tmp_df), tmp_df)
        
        rownames(tmp_df) <- 1:nrow(tmp_df)
        
        tmp_df <-
          tmp_df %>% mutate(version = contents$version,
                            category_label = contents$label,
                            href = contents$href,
                            extension_id = contents$extension$id,
                            extension_description = contents$extension$description,
                            class = contents$class,
                            source = contents$source)
        
        full_df <- rbind(full_df, tmp_df)
        
      },
      error = function(e) {
        # There's no need for error message in simple export function
        # message("Erro: \n")
        # print(e)
        row = row + 1
      })
      
    }
    
    return(
      save_output(
        r_object = full_df,
        file_directory = "raw",
        file_name = "bpstat_domain_description",
        extension = extension
      )
    )
  }
  
    
}

